### ISSUE TITLE
Is there a way to change the sort order for list view?

### ISSUE THREAD

**Issue by jakehawkes** [woodwardtw/gfolder_embed#3]
I think at the moment it is alpha-numeric in ascending order. Is there a way to reverse this?

**Comment by woodwardtw** [comment]
I'm waaaay late responding but it doesn't look like the iframe respects the sort options available via the API. Even with the plain URL, the sort options seem to fail.[ I tried the orderBy parameter from this part of the documentation](https://developers.google.com/drive/api/v3/reference/files/list).
