### ISSUE TITLE
Add optional resourcekey for shared forlder

### ISSUE THREAD

**Issue by maxime915** [woodwardtw/gfolder_embed#5]
Sharing some folder produce a 403 forbidden error when sharing without resourcekey, as pointed out by https://stackoverflow.com/a/69422689/5770818 . This seems to be caused by a "recent" modification of the term of uses (I have no source for this).

It would be awesome to have a resourcekey attribute when sharing the folder, such that the view work again. I understand adding this field could break compatibility, perhaps there is a way to add it as an optional attribute, see an idea below.

```php

if (array_key_exists("resourcekey", $atts)) {
    $a = shortcode_atts( array(
         'id' => '',
         'style' => 'list',
         'width' => '100%',
         'height' => '500px',
         'resourcekey' => 'resourcekey',
    ), $atts); 
	return '<iframe src="https://drive.google.com/embeddedfolderview?id=' . $a['id'] . '&resourcekey=' . $a['resourcekey'] . '#' . $a['style'] . '" frameborder="0" width="' . $a['width'] . '" height="' . $a['height'].'" scrolling="auto"> </iframe>';
} else {
    $a = shortcode_atts( array(
         'id' => '',
         'style' => 'list',
         'width' => '100%',
         'height' => '500px',
    ), $atts); 
	return '<iframe src="https://drive.google.com/embeddedfolderview?id=' . $a['id'] . '#' . $a['style'] . '" frameborder="0" width="' . $a['width'] . '" height="' . $a['height'].'" scrolling="auto"> </iframe>';
}

```

**Comment by woodwardtw** [comment]
Thanks. I updated it and it shouldn't harm any previous codes. It's a bit cleaner too. 

I also tried to get sorting working but best I can tell the iframe doesn't respect the api parameters.
